### ISSUE TITLE
Error: FormErrorsExtension::__construct() must be an instance of Ex3v\FormErrorsBundle\Twig\Translator

### ISSUE THREAD

**Issue by h3llr4iser** [Ex3v/FormErrorsBundle#8]
I have symfony 2.7 and I have this error
ContextErrorException in FormErrorsExtension.php line 27: Catchable Fatal Error: Argument 2 passed to Ex3v\FormErrorsBundle\Twig\FormErrorsExtension::__construct() must be an instance of Ex3v\FormErrorsBundle\Twig\Translator

You should change the class FormErrorsExtension construct to:

      public function __construct(FormErrorsParser $parser, TranslatorInterface $trans)
      {
            $this->parser = $parser;
            $this->trans =  $trans ;
      }

**Comment by Ex3v** [comment]
Thanks for fix!
